//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 HospitalManage.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HOSPITALMANAGE_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_DETAIL               130
#define IDD_DIALOG_CHECK                132
#define IDD_DIALOG_DRUG                 134
#define IDD_DIALOG_ADD                  136
#define IDD_DIALOG_SEARCH               138
#define IDD_DIALOG_INFO                 140
#define IDD_DIALOG_DEPOSIT              142
#define IDD_DIALOG_Doctor               144
#define IDD_DIALOG_DoctorDetail         146
#define IDD_DIALOG_PREDICT              148
#define IDC_LIST1                       1000
#define IDC_BUTTON_FILE                 1001
#define IDC_BUTTON_ADD                  1002
#define IDC_BUTTON_DELETE               1003
#define IDC_BUTTON_SEARCH               1004
#define IDC_BUTTON_INFO                 1005
#define IDC_BUTTON_SAVE                 1006
#define IDC_TAB1                        1029
#define IDC_EDIT_PatientName            1030
#define IDC_EDIT_PatientAge             1031
#define IDC_EDIT_PatientID              1032
#define IDC_EDIT_DoctorGrade            1034
#define IDC_EDIT_DoctorID               1036
#define IDC_BUTTON_ChangeBasic          1037
#define IDC_LIST_CHECK                  1038
#define IDC_EDIT_CheckYuan              1039
#define IDC_EDIT_DrugYuan               1042
#define IDC_LIST_DRUG                   1047
#define IDC_EDIT_Deposit                1050
#define IDC_BUTTON_YES                  1051
#define IDC_BUTTON_NO                   1052
#define IDC_DATETIMEPICKER_Start        1057
#define IDC_DATETIMEPICKER_End          1058
#define IDC_BUTTON_AddDeposit           1059
#define IDC_BUTTON_OUT                  1060
#define IDC_STATIC1                     1061
#define IDC_STATIC2                     1062
#define IDC_STATIC3                     1063
#define IDC_STATIC7                     1064
#define IDC_STATIC4                     1065
#define IDC_STATIC5                     1066
#define IDC_STATIC8                     1067
#define IDC_STATIC10                    1068
#define IDC_STATIC14                    1072
#define IDC_STATIC18                    1076
#define IDC_STATIC19                    1077
#define IDC_STATIC20                    1078
#define IDC_STATIC21                    1079
#define IDC_BUTTON_OK                   1081
#define IDC_BUTTON_CANCLE               1082
#define IDC_EDIT_FEE                    1084
#define IDC_BUTTON_Y                    1086
#define IDC_EDIT_NUM                    1089
#define IDC_EDIT_PRICE                  1090
#define IDC_EDIT1                       1091
#define IDC_EDIT2                       1092
#define IDC_EDIT3                       1093
#define IDC_DATETIMEPICKER1             1095
#define IDC_COMBO1                      1097
#define IDC_COMBO_DoctorName            1098
#define IDC_EDIT5                       1099
#define IDC_EDIT6                       1100
#define IDC_RADIO2                      1101
#define IDC_RADIO3                      1102
#define IDC_RADIO4                      1103
#define IDC_EDIT7                       1105
#define IDC_BUTTON2                     1106
#define IDC_LIST2                       1107
#define IDC_EDIT8                       1110
#define IDC_DATETIMEPICKER2             1111
#define IDC_DATETIMEPICKER3             1112
#define IDC_EDIT9                       1113
#define IDC_EDIT_Department             1120
#define IDC_EDIT_DoctorName             1121
#define IDC_EDIT_Count                  1122
#define IDC_EDIT_Item                   1123
#define IDC_EDIT_DrugName               1124
#define IDC_EDIT_YaJin                  1125
#define IDC_COMBO_Department            1126
#define IDC_RADIO1                      1127
#define IDC_COMBO2                      1128
#define IDC_EDIT_Name                   1129
#define IDC_EDIT_Age                    1130
#define IDC_DATETIMEPICKER_From         1131
#define IDC_DATETIMEPICKER_TO           1132
#define IDC_RADIO5                      1133
#define IDC_RADIO6                      1134
#define IDC_RADIO7                      1135
#define IDC_BUTTON_ShanChu              1137
#define IDC_BUTTON_ZhuYuan              1138
#define IDC_LIST_ZhuYuan                1139
#define IDC_EDIT_Turnover               1140
#define IDC_DATETIMEPICKER_System       1141
#define IDC_BUTTON_DOCTOR               1142
#define IDC_LIST_Doctor                 1143
#define IDC_BUTTON_AddDoctor            1144
#define IDC_EDIT_Room                   1145
#define IDC_STATIC11                    1146
#define IDC_COMBO_Type                  1147
#define IDC_COMBO_Room                  1148
#define IDC_COMBO_Nurse                 1149
#define IDC_COMBO_KeShi                 1150
#define IDC_EDIT_ID                     1151
#define IDC_CHECK1                      1153
#define IDC_CHECK2                      1154
#define IDC_CHECK3                      1155
#define IDC_CHECK4                      1156
#define IDC_CHECK5                      1157
#define IDC_CHECK6                      1158
#define IDC_CHECK7                      1159
#define IDC_COMBO_Grade                 1160
#define IDC_COMBO_State                 1161
#define IDC_EDIT_PateintID              1162
#define IDC_LIST_Room                   1163
#define IDC_BUTTON_RoomAdjust           1164
#define IDC_BUTTON_Predict              1165
#define IDC_COMBO_Select                1166
#define IDC_EDIT_Fourth                 1167
#define IDC_EDIT_Result                 1168
#define IDC_EDIT_First                  1169
#define IDC_EDIT_Second                 1170
#define IDC_EDIT_Third                  1171
#define IDC_EDIT_Fifth                  1172
#define IDC_BUTTON1                     1173
#define IDC_BUTTON_StartPredict         1174
#define IDC_BUTTON3                     1175
#define IDC_BUTTON_SearchOK             1176
#define IDC_BUTTON_SearchCancle         1177

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1178
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
